# ==================== 服务器端口配置 ====================
server:
  # 应用启动端口
  port: 8080

# ==================== Spring 全局配置 ====================
spring:
  # 激活的配置文件（dev/prod/test）
  profiles:
    active: dev
  main:
    # 允许循环依赖（Spring Boot 2.6+ 默认禁止）
    allow-circular-references: true
  # ==================== 数据源配置 ====================
  datasource:
    # MySQL 驱动类名
    driver-class-name: ${sky.datasource.driver-class-name}
    # 数据库连接 URL：时区、编码、SSL、公钥检索等参数
    url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    # 数据库用户名
    username: ${sky.datasource.username}
    # 数据库密码
    password: ${sky.datasource.password}
  data:
    redis:
      host: ${sky.redis.host}
      port: ${sky.redis.port}
      password: ${sky.redis.password}
      database: ${sky.redis.database}

# ==================== springdoc-openapi（Swagger 3）配置 ====================
springdoc:
  api-docs:
    # 是否启用 OpenAPI 3 接口文档
    enabled: true
    # 接口文档的访问路径
    path: /v3/api-docs
  swagger-ui:
    # 是否启用 Swagger UI
    enabled: true
    # Swagger UI 的访问路径
    path: /swagger-ui/index.html
  # 扫描所有 Controller 包
  packages-to-scan: com.sky.controller
  # 匹配所有路径
  paths-to-match: /**
  # API 分组配置：按 admin / user 拆分
  group-configs:
    - group: admin
      packages-to-scan: com.sky.controller.admin
      paths-to-match: /admin/**
    - group: user
      packages-to-scan: com.sky.controller.user
      paths-to-match: /user/**

# ==================== OpenAPI 文档元数据配置 ====================
# 定义 API 文档的标题、描述、版本等全局信息
openapi:
  info:
    # API 文档标题
    title: 苍穹外卖项目 API 文档
    # API 文档详细描述
    description: 苍穹外卖项目的后台管理系统和移动端用户的API接口文档。
    # API 版本号
    version: 1.0.0

# ==================== MyBatis-Plus 配置 ====================
mybatis-plus:
  # 实体类所在包路径（用于别名扫描）
  type-aliases-package: com.sky.entity
  configuration:
    # 开启驼峰命名自动映射（user_name → userName）
    map-underscore-to-camel-case: true

# ==================== 日志级别配置 ====================
logging:
  level:
    com:
      sky:
        # Mapper 层日志：打印 SQL
        mapper: debug
        # Service 层日志：INFO 级别
        service: info
        # Controller 层日志：INFO 级别
        controller: info

# ==================== 项目自定义配置（sky 前缀） ====================
sky:
  # ==================== JWT 配置 ====================
  jwt:
    # 管理端 JWT 签名密钥（长度 ≥ 256 bit，生产环境请使用环境变量注入）
    admin-secret-key: ZK8fM1pQk9s2cT7vR4xY9aL3uN6eB2dH
    # 管理端 JWT 过期时间（单位：毫秒，2 小时）
    admin-ttl: 7200000
    # 管理端前端传递的令牌名称
    admin-token-name: token
    # （可选）用户端 JWT 密钥；生产环境建议使用环境变量注入
    # user-secret-key: A2b4D6f8H0j2L4n6P8r0T2v4X6z8B0d2F4h6J8k0M2q4S6u8W0y2C4e6G8

  # ==================== 阿里云 OSS 配置 ====================
  alioss:
    # OSS 访问端点
    endpoint: ${sky.alioss.endpoint}
    # AccessKey ID
    access-key-id: ${sky.alioss.access-key-id}
    # AccessKey Secret
    access-key-secret: ${sky.alioss.access-key-secret}
    # 存储空间名称
    bucket-name: ${sky.alioss.bucket-name}
