# 项目自定义配置
sky:
  # 数据库连接配置
  datasource:
    # MySQL 8.x JDBC 驱动类名
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库服务器地址
    host: localhost
    # 数据库服务端口
    port: 3306
    # 数据库名称
    database: sky_take_out
    # 数据库登录用户名
    username: root
    # 数据库登录密码
    password: 123456
  # 阿里云 OSS 对象存储配置
  alioss:
    # OSS 访问域名（广州区域）
    endpoint: oss-cn-guangzhou.aliyuncs.com
    # 阿里云 AccessKey ID，用于身份认证
    access-key-id: LTAI5tPHMrLCVAkEdeNBkY1Q
    # 阿里云 AccessKey Secret，用于身份认证（请妥善保管）
    access-key-secret: kOviRxEwkRM8HXZwqA4pMlruexUiwM
    # OSS 存储空间名称
    bucket-name: sky-take-out-fileupload-necoocean