# 项目自定义配置（开发环境）
sky:
  # 数据库连接配置
  datasource:
    # MySQL 8.x JDBC 驱动类名
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库服务器地址
    host: localhost
    # 数据库服务端口
    port: 3306
    # 数据库名称
    database: sky_take_out
    # 数据库登录用户名
    username: root
    # 数据库登录密码
    password: 123456
  # 阿里云 OSS 对象存储配置
  alioss:
    # OSS 访问域名（广州区域）
    endpoint: oss-cn-guangzhou.aliyuncs.com
    # 阿里云 AccessKey ID，用于身份认证（生产环境请用环境变量注入）
    access-key-id: LTAI5tPHMrLCVAkEdeNBkY1Q
    # 阿里云 AccessKey Secret，用于身份认证（生产环境请用环境变量注入，切勿提交到代码仓库）
    access-key-secret: kOviRxEwkRM8HXZwqA4pMlruexUiwM
    # OSS 存储空间名称
    bucket-name: sky-take-out-fileupload-necoocean
  # Redis 缓存配置
  redis:
    # Redis 服务器地址
    host: localhost
    # Redis 服务器端口
    port: 6379
    # Redis 登录密码（如无密码可留空）
    password: 123456
    # Redis 数据库索引（默认0）
    database: 0
  # 微信支付/小程序相关配置
  wechat:
    # 微信小程序appid
    appid: wx3ce902cdbae52ec9
    # 微信小程序secret
    secret: 34256494d5bcc560b47ed2f9fa11350b
    # 商户号（如需支付功能请填写）
    mchid: 
    # 商户证书序列号（如需支付功能请填写）
    mchSerialNo: 
    # 商户私钥文件路径（如需支付功能请填写）
    privateKeyFilePath: 
    # API v3密钥（如需支付功能请填写）
    apiV3Key: 
    # 微信支付平台证书文件路径（如需支付功能请填写）
    weChatPayCertFilePath: 
    # 支付结果通知地址（如需支付功能请填写）
    notifyUrl: 
    # 退款结果通知地址（如需支付功能请填写）
    refundNotifyUrl: